# Generated by Django 4.0.3 on 2022-06-07 19:52

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cwf',
            fields=[
                ('cwf_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Excel',
            fields=[
                ('excel_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=250)),
                ('alt_text', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('exhibit_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=250)),
                ('alt_text', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kt',
            fields=[
                ('kt_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('cwf', models.ManyToManyField(to='cms.cwf')),
            ],
        ),
        migrations.CreateModel(
            name='Qtype',
            fields=[
                ('qtype_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_code', models.CharField(max_length=20, unique=True)),
                ('role_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('access_role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('stage_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('role', models.ManyToManyField(to='cms.role')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('context', models.JSONField()),
                ('text', models.CharField(max_length=100)),
                ('options', models.JSONField()),
                ('score_type', models.CharField(max_length=10)),
                ('score_weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('resources', models.JSONField()),
                ('last_edited', models.DateTimeField(default=datetime.datetime.now)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_approver', to='cms.user')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_creator', to='cms.user')),
                ('cwf', models.ManyToManyField(to='cms.cwf')),
                ('excels', models.ManyToManyField(to='cms.excel')),
                ('exhibits', models.ManyToManyField(to='cms.exhibit')),
                ('kt', models.ManyToManyField(to='cms.kt')),
                ('last_edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_editor', to='cms.user')),
                ('qtype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.qtype')),
                ('role', models.ManyToManyField(to='cms.role')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.stage')),
            ],
        ),
        migrations.AddField(
            model_name='kt',
            name='role',
            field=models.ManyToManyField(to='cms.role'),
        ),
        migrations.AddField(
            model_name='cwf',
            name='role',
            field=models.ManyToManyField(to='cms.role'),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('problem_statement', models.CharField(blank=True, max_length=1000)),
                ('remarks', models.CharField(blank=True, max_length=1000)),
                ('last_updated', models.DateTimeField(default=datetime.datetime.now)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_approver', to='cms.user')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_creator', to='cms.user')),
                ('questions', models.ManyToManyField(to='cms.question')),
                ('role', models.ManyToManyField(to='cms.role')),
            ],
        ),
    ]
