# Generated by Django 4.0.5 on 2022-06-23 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='question',
            field=models.ForeignKey(default=1998, on_delete=django.db.models.deletion.CASCADE, related_name='commentor', to='cms.question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='mentioned',
            field=models.ManyToManyField(blank=True, related_name='question_mentioned', to=settings.AUTH_USER_MODEL),
        ),
    ]
