# Generated by Django 4.0.5 on 2022-06-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='questions',
            field=models.ManyToManyField(blank=True, to='cms.question'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='role',
            field=models.ManyToManyField(blank=True, to='cms.role'),
        ),
        migrations.AlterField(
            model_name='question',
            name='cwf',
            field=models.ManyToManyField(blank=True, to='cms.cwf'),
        ),
        migrations.AlterField(
            model_name='question',
            name='excels',
            field=models.ManyToManyField(blank=True, to='cms.excel'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exhibits',
            field=models.ManyToManyField(blank=True, to='cms.exhibit'),
        ),
        migrations.AlterField(
            model_name='question',
            name='kt',
            field=models.ManyToManyField(blank=True, to='cms.kt'),
        ),
        migrations.AlterField(
            model_name='question',
            name='role',
            field=models.ManyToManyField(blank=True, to='cms.role'),
        ),
    ]
