# Generated by Django 4.0.5 on 2022-06-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_assessment_questions_alter_assessment_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='context',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='resources',
            field=models.JSONField(blank=True),
        ),
    ]
