# Generated by Django 4.0.5 on 2022-06-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_assessment_assigned_to_assessment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('ADMIN', 'Admin')], default='Member', max_length=20),
        ),
    ]
