# Generated by Django 4.0.5 on 2022-06-23 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_comment_mentioned_alter_question_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excel',
            name='url',
        ),
        migrations.RemoveField(
            model_name='exhibit',
            name='url',
        ),
        migrations.RemoveField(
            model_name='question',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='last_updated_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='excel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='excel',
            name='file',
            field=models.FileField(blank=True, upload_to='exhibits/'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='image',
            field=models.ImageField(blank=True, upload_to='exhibits/'),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='idealtime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='misc',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('SAVED', 'Saved'), ('UNDERREVIEW', 'Under Review'), ('REVIEWED', 'Reviewed'), ('ARCHIVED', 'Archived')], default='SAVED', max_length=20),
        ),
    ]
